In [2]:
import pandas as pd
import numpy as np

In [3]:
pd.options.display.float_format = '{:,.2f}'.format

In [10]:
np.set_printoptions(precision=1)

In [11]:
x1 = np.random.rand(2,5)*10
x1

array([[6.1, 6.2, 3.4, 5. , 9.3],
       [0.8, 2.7, 3.7, 2.4, 8.4]])

In [12]:
x2 = np.random.rand(2,5)*-1
x2

array([[-0.5, -0.7, -0.3, -0.5, -1. ],
       [-1. , -0.2, -0. , -0.7, -0.9]])

In [13]:
np.concatenate([x1,x2])

array([[ 6.1,  6.2,  3.4,  5. ,  9.3],
       [ 0.8,  2.7,  3.7,  2.4,  8.4],
       [-0.5, -0.7, -0.3, -0.5, -1. ],
       [-1. , -0.2, -0. , -0.7, -0.9]])

In [15]:
np.concatenate([x1,x2], axis=1)

array([[ 6.1,  6.2,  3.4,  5. ,  9.3, -0.5, -0.7, -0.3, -0.5, -1. ],
       [ 0.8,  2.7,  3.7,  2.4,  8.4, -1. , -0.2, -0. , -0.7, -0.9]])

In [21]:
s1 = pd.Series(x1[0], index=['a', 'b', 'c', 'd', 'e'])
s1

a   6.11
b   6.24
c   3.43
d   4.96
e   9.34
dtype: float64

In [22]:
s2 = pd.Series(x1[0], index=['c', 'd', 'e', 'f', 'g'])
s2

c   6.11
d   6.24
e   3.43
f   4.96
g   9.34
dtype: float64

In [24]:
pd.concat([s1,s2], axis = 1)

0    1
a 6.11  nan
b 6.24  nan
c 3.43 6.11
d 4.96 6.24
e 9.34 3.43
f  nan 4.96
g  nan 9.34

In [25]:
s1.reset_index(drop=True)

0   6.11
1   6.24
2   3.43
3   4.96
4   9.34
dtype: float64

In [26]:
pd.concat([s1.reset_index(drop=True), s2.reset_index(drop=True)], axis=1)

0    1
0 6.11 6.11
1 6.24 6.24
2 3.43 3.43
3 4.96 4.96
4 9.34 9.34

In [28]:
df1 = pd.DataFrame(np.random.rand(3,2)*10, columns=['a','b'])
df1

a    b
0 5.02 0.46
1 7.59 7.12
2 2.17 7.61

In [29]:
df2 = pd.DataFrame(np.random.rand(3,2)*-1, columns=['a','b'], index=[2,3,4])
df2

a     b
2 -0.51 -0.42
3 -0.26 -0.08
4 -0.18 -0.75

In [30]:
pd.concat([df1, df2])

a     b
0  5.02  0.46
1  7.59  7.12
2  2.17  7.61
2 -0.51 -0.42
3 -0.26 -0.08
4 -0.18 -0.75

In [31]:
pd.concat([df1, df2], axis = 1)

a    b     a     b
0 5.02 0.46   nan   nan
1 7.59 7.12   nan   nan
2 2.17 7.61 -0.51 -0.42
3  nan  nan -0.26 -0.08
4  nan  nan -0.18 -0.75

In [32]:
pd.concat([df1, df2], axis = 1, join='inner')

a    b     a     b
2 2.17 7.61 -0.51 -0.42

In [33]:
#concatenar sin tener en cuenta los indices
pd.concat([df1.reset_index(drop=True),
           df2.reset_index(drop=True)
           ], axis = 1)

a    b     a     b
0 5.02 0.46 -0.51 -0.42
1 7.59 7.12 -0.26 -0.08
2 2.17 7.61 -0.18 -0.75

In [35]:
df1.append(df2).append(df2)

a     b
0  5.02  0.46
1  7.59  7.12
2  2.17  7.61
2 -0.51 -0.42
3 -0.26 -0.08
4 -0.18 -0.75
2 -0.51 -0.42
3 -0.26 -0.08
4 -0.18 -0.75

In [36]:
df1.T.append(df2.T).T

a    b     a     b
0 5.02 0.46   nan   nan
1 7.59 7.12   nan   nan
2 2.17 7.61 -0.51 -0.42
3  nan  nan -0.26 -0.08
4  nan  nan -0.18 -0.75